### PR TITLE
Added support for markdown in stories

### LINKED ISSUE #17: Allow proper markup in stories.

### PR DESCRIPTION
**Pull request by polybuildr**
Should resolve #17.

### CODE REVIEW

**Comment by polybuildr** [comment]
Man, the rest of the code needs a cleanup. :P I've tried to keep my changes as minimal as possible, but my editor's defaults fixed the line endings, trailing spaces at the end of lines and the missing newlines at the end of files.

Also, I'm not sure this works, primarily because the repo wouldn't work for me out of the box, so please review before merging.

**Comment by ParthKolekar** [comment]
@polybuildr , Are you PR'ing to fix another PR? :grin: 

Also fixed in #24

**Comment by ParthKolekar** [comment]
@polybuildr Are you PR'ing to fix another PR? :grin:

**Comment by polybuildr** [comment]
@ParthKolekar, what other PR?

**Comment by amoghbl1** [comment]
@mrinaldhar Could you test this out and merge it?

**Comment by mrinaldhar** [comment]
Looks good. Merged.

**Pull request merged**
