### PR TITLE
Major coding style and file structure fixes

### PR DESCRIPTION
**Pull request by nisargjhaveri**
Also give a link to GitHub contributors

### CODE REVIEW

**Comment by amoghbl1** [comment]
There was a PR before this that I merged... Think you need to update it!

**Comment by ffledgling** [comment]
@mrinaldhar Since you wrote the original, you should probably the one to review this PR.

@nisargjhaveri I think this needs a rebase, it's based off of a version when `css/*` didn't exist.
You might also want to fix #12 before you proceed with this.

**Comment by mrinaldhar** [comment]
Since we decided to paginate the website now, there is no 'main' js and css. I usually follow this convention while naming js and css files:
1. Files that are specific to a certain HTML file take the same name as the HTML file. 
(index.css, stories.css)
2. File that is common to all takes the name standard.css/standard.js

Also, since we don't have a near-release version yet, and I'm constantly going into code to make big changes, I'd prefer it if we hold off coding style fixes. We also have an issue created for that, lets see where that discussion goes and then we can modify the code for the existing files.

**Comment by nisargjhaveri** [comment]
This PR coincided with similar PR by @mrinaldhar. I think a  rebase won't work anymore.

The best is to close this now and redo it later. Closing now.

**Comment by ffledgling** [comment]
wfm!

**Pull request closed without merging**
