### PR TITLE
Major Changes. See description.

### PR DESCRIPTION
**Pull request by mrinaldhar**
Changelog: 
1. Website pagination introduced. 
2. Fixed logo issues. 
3. Stories page almost ready.

### CODE REVIEW

**Comment by ffledgling** [comment]
Is the npm-debug.log intentionally a part of this? Or is an an over sight from `git commit -am` ?

**Comment by ffledgling** [comment]
Also, a screenshot of the new changes would be awesome.

**Comment by mrinaldhar** [comment]
screen shot 2015-07-20 at 11 40 14 pm
screen shot 2015-07-20 at 11 41 00 pm

**Comment by mrinaldhar** [comment]
The npm log is unintentional. I'll remove it in next code update.

**Comment by mrinaldhar** [comment]
It's live at http://osdg.iiit.ac.in/staging/ too, if you wanna check it out.

**Comment by ffledgling** [comment]
GAH people, don't merge without reviewing! cc: @amoghbl1 
Atleast have @nisargjhaveri or someone do a sanity check. Atleast for major changes :P

**Comment by amoghbl1** [comment]
Ya, I'll do that for the next ones @ffledgling.

**Pull request merged**
