### PR TITLE
Cleaned up indentation and spacing of js and css

### PR DESCRIPTION
**Pull request by polybuildr**

### CODE REVIEW

**Comment by polybuildr** [comment]
Relevant to #12.

**Comment by polybuildr** [comment]
Picked tabs since they were more prevalent.

**Comment by ParthKolekar** [comment]
Fixed in #26 

Why picked tabs? 
It is spaces, 4 everywhere. 

Everywhere.

**Comment by polybuildr** [comment]
@ParthKolekar, #26 is my PR regarding DOS line endings. This is an independent issue. (..?)

And picked tabs because I had no idea what convention was going to be followed, but tabs were being used almost everywhere at the time of the PR.

**Comment by amoghbl1** [comment]
@mrinaldhar What exactly is the convention we plan on using??

**Comment by mrinaldhar** [comment]
I'm in favor of tabs, but that was just the initial code I wrote. Do what you think is best.

**Pull request merged**
